#!/usr/bin/env python3
"""
Customer Configuration Script

Interactive script to configure the chatbot for a new customer.
Generates .env file with customer-specific settings.

Usage:
    python scripts/configure-customer.py

The script will prompt you for:
- Customer/project name
- OpenAI API key
- Assistant behavior preferences
- Branding preferences
"""

import os
import sys
from pathlib import Path
from typing import Optional


def prompt(question: str, default: Optional[str] = None, required: bool = True) -> str:
    """Prompt user for input with optional default value."""
    if default:
        question = f"{question} [{default}]"
    question = f"{question}: "

    while True:
        response = input(question).strip()
        if response:
            return response
        if default:
            return default
        if not required:
            return ""
        print("  This field is required. Please enter a value.")


def prompt_choice(question: str, choices: list[str], default: Optional[str] = None) -> str:
    """Prompt user to choose from a list of options."""
    print(f"\n{question}")
    for i, choice in enumerate(choices, 1):
        marker = " (default)" if choice == default else ""
        print(f"  {i}. {choice}{marker}")

    while True:
        response = input(f"Choice [1-{len(choices)}]: ").strip()
        if not response and default:
            return default
        try:
            index = int(response) - 1
            if 0 <= index < len(choices):
                return choices[index]
        except ValueError:
            pass
        print(f"  Please enter a number between 1 and {len(choices)}")


def prompt_multiline(question: str, default: Optional[str] = None) -> str:
    """Prompt for multiline input."""
    print(f"\n{question}")
    if default:
        print(f"(Press Enter to use default, or type your own. End with Ctrl+D or empty line)")
        print(f"\nDefault:\n{default}\n")
    else:
        print("(End with Ctrl+D or empty line)")

    lines = []
    try:
        while True:
            line = input()
            if not line and lines:  # Empty line after some input
                break
            lines.append(line)
    except EOFError:
        pass

    text = "\n".join(lines).strip()
    return text if text else (default or "")


def generate_env_file(config: dict, output_path: Path) -> None:
    """Generate .env file from configuration."""
    content = f'''# Customer Chatbot Configuration
# Generated by scripts/configure-customer.py

# ==============================================================================
# OPENAI CONFIGURATION
# ==============================================================================

# Required: Your OpenAI API key
OPENAI_API_KEY={config['openai_api_key']}

# Required: Vector Store ID (run scripts/setup-vector-store.py to create)
VECTOR_STORE_ID={config.get('vector_store_id', '')}

# ==============================================================================
# ASSISTANT CONFIGURATION
# ==============================================================================

# Customer/Project name
ASSISTANT_NAME={config['assistant_name']}

# AI Model to use
ASSISTANT_MODEL={config['assistant_model']}

# Response creativity (0.0 = deterministic, 1.0 = creative)
ASSISTANT_TEMPERATURE={config['assistant_temperature']}

# Maximum document chunks to retrieve per query
MAX_SEARCH_RESULTS={config['max_search_results']}

# ==============================================================================
# SERVER CONFIGURATION
# ==============================================================================

# Server host and port
SERVER_HOST=127.0.0.1
SERVER_PORT=8002

# CORS origins (comma-separated, use * for dev, specific domains for production)
CORS_ORIGINS={config['cors_origins']}

# Log level
LOG_LEVEL=INFO

# ==============================================================================
# FRONTEND CONFIGURATION (for Vite)
# ==============================================================================

# API base URL
VITE_KNOWLEDGE_API_BASE=/knowledge

# ChatKit API endpoint
VITE_KNOWLEDGE_CHATKIT_API_URL=/knowledge/chatkit

# Domain key (use real key for production, any string for localhost)
VITE_KNOWLEDGE_CHATKIT_API_DOMAIN_KEY=domain_pk_localhost_dev

# Documents endpoint
VITE_KNOWLEDGE_DOCUMENTS_URL=/knowledge/documents

# Welcome greeting
VITE_KNOWLEDGE_GREETING={config['greeting']}

# Composer placeholder
VITE_KNOWLEDGE_COMPOSER_PLACEHOLDER={config['composer_placeholder']}

# Starter prompts (comma-separated)
VITE_KNOWLEDGE_STARTER_PROMPTS={config.get('starter_prompts', '')}
'''

    output_path.write_text(content)
    print(f"\n✓ Configuration saved to {output_path}")


def main():
    print("=" * 70)
    print(" Customer Chatbot Configuration")
    print("=" * 70)
    print("\nThis wizard will help you configure the chatbot for a new customer.")
    print("You can skip optional fields by pressing Enter.\n")

    config = {}

    # Basic configuration
    print("\n" + "=" * 70)
    print(" 1. BASIC CONFIGURATION")
    print("=" * 70)

    config['assistant_name'] = prompt(
        "Customer/Project name (e.g., 'Acme Corp Knowledge Assistant')",
        default="Knowledge Assistant"
    )

    config['openai_api_key'] = prompt(
        "OpenAI API key (get from https://platform.openai.com/api-keys)",
        default=os.getenv("OPENAI_API_KEY", "")
    )

    # AI Model selection
    print("\n" + "=" * 70)
    print(" 2. AI MODEL CONFIGURATION")
    print("=" * 70)

    model_choices = [
        "gpt-4.1-mini (Fast, cost-effective, good for most use cases)",
        "gpt-4o (More capable, better reasoning)",
        "gpt-4o-mini (Balanced performance and cost)",
    ]
    model_map = {
        model_choices[0]: "gpt-4.1-mini",
        model_choices[1]: "gpt-4o",
        model_choices[2]: "gpt-4o-mini",
    }

    selected_model = prompt_choice(
        "Which AI model would you like to use?",
        model_choices,
        default=model_choices[0]
    )
    config['assistant_model'] = model_map[selected_model]

    # Temperature selection
    temp_choices = [
        "Low (0.0-0.3) - Consistent, factual responses (recommended for knowledge bases)",
        "Medium (0.4-0.6) - Balanced creativity and consistency",
        "High (0.7-1.0) - More creative and varied responses",
    ]
    temp_map = {
        temp_choices[0]: "0.3",
        temp_choices[1]: "0.5",
        temp_choices[2]: "0.8",
    }

    selected_temp = prompt_choice(
        "How creative should the responses be?",
        temp_choices,
        default=temp_choices[0]
    )
    config['assistant_temperature'] = temp_map[selected_temp]

    # Search results
    config['max_search_results'] = prompt(
        "Maximum document chunks to retrieve per query (3-10 recommended)",
        default="5"
    )

    # Frontend configuration
    print("\n" + "=" * 70)
    print(" 3. FRONTEND CONFIGURATION")
    print("=" * 70)

    config['greeting'] = prompt(
        "Welcome greeting for users",
        default=f"Welcome to {config['assistant_name']}. Ask me anything about our knowledge base."
    )

    config['composer_placeholder'] = prompt(
        "Input field placeholder text",
        default="Ask a question..."
    )

    print("\nStarter prompts (optional - example questions to show users)")
    print("Enter prompts one per line, or press Enter to skip:")
    prompts = []
    for i in range(3):
        p = prompt(f"  Prompt {i+1}", default="", required=False)
        if p:
            prompts.append(p)

    config['starter_prompts'] = "|".join(prompts) if prompts else ""

    # Deployment configuration
    print("\n" + "=" * 70)
    print(" 4. DEPLOYMENT CONFIGURATION")
    print("=" * 70)

    env_choice = prompt_choice(
        "Deployment environment?",
        ["Development (allow all origins)", "Production (restrict to specific domain)"],
        default="Development (allow all origins)"
    )

    if "Production" in env_choice:
        domain = prompt("Frontend domain (e.g., https://customer.example.com)")
        config['cors_origins'] = domain
    else:
        config['cors_origins'] = "*"

    # Summary
    print("\n" + "=" * 70)
    print(" CONFIGURATION SUMMARY")
    print("=" * 70)
    print(f"\n  Assistant Name: {config['assistant_name']}")
    print(f"  Model: {config['assistant_model']}")
    print(f"  Temperature: {config['assistant_temperature']}")
    print(f"  Max Results: {config['max_search_results']}")
    print(f"  Greeting: {config['greeting'][:60]}...")
    print(f"  CORS Origins: {config['cors_origins']}")

    confirm = prompt("\nSave this configuration? (yes/no)", default="yes")
    if confirm.lower() not in ['yes', 'y']:
        print("\n❌ Configuration cancelled.")
        sys.exit(0)

    # Generate .env file
    project_root = Path(__file__).parent.parent
    env_path = project_root / ".env"

    if env_path.exists():
        backup = env_path.with_suffix(".env.backup")
        env_path.rename(backup)
        print(f"\n💾 Existing .env backed up to {backup}")

    generate_env_file(config, env_path)

    print("\n" + "=" * 70)
    print(" ✅ CONFIGURATION COMPLETE!")
    print("=" * 70)
    print("\n📋 Next steps:")
    print("   1. Add documents to backend/data/ directory")
    print("   2. Run: python scripts/setup-vector-store.py")
    print("   3. Review/customize: backend/app/config.py")
    print("   4. Start backend: cd backend && uvicorn app.main:app --reload")
    print("   5. Start frontend: cd frontend && npm run dev")
    print("\n💡 Tip: You can edit .env file directly to fine-tune settings")


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        print("\n\n❌ Configuration cancelled by user.")
        sys.exit(0)
